### ISSUE TITLE
Use lsgkm-SVM from kipoi/models on new data

### ISSUE THREAD

**Issue by lzamparo** [kipoi/models#101]
I'd like to use the lsgkm-SVM model for comparing performance on new data, but don't see a demonstration of that use case in the docs.  Could you suggest some tips for where to start?  The task is to predict ChIP binding from sequence.

At a minimum, I'll have to implement my own dataloader to process and serve my training data.  But it also seems like there is no provision for re-training any models, just for making canned predictions.  Is this so?

**Comment by Avsecz** [comment]
Search for the appropriate TF of interest here: http://kipoi.org/groups/lsgkm-SVM/Tfbs/.

You can implement your own dataloader (folder with dataloader.py and dataloader.yaml). In that case you can directly use Kipoi:
`kipoi predict ... --dataloader=path/to/dataloader --dataloader_source=dir ...

**Comment by lzamparo** [comment]
Are you referring to the authors provided implementation [here](https://github.com/Dongwon-Lee/lsgkm)?  And if so, could you point me to any code from Kipoi that I could re-use as a python interface to the compiled lsgkm binary? 

One additional problem: the DOI for the ls-gkmsvm paper [here](https://doi.org/10.1016/j.cell.2015.09.054) resolves incorrectly; it does not point to the ls-gkmsvm paper, but to an [MPRA paper](https://www.sciencedirect.com/science/article/pii/S0092867415012714?via%3Dihub) by the Shendure group

**Comment by lzamparo** [comment]
Also, trying to load one of the given TF models using the pattern laid out in the quick start triggers an un-caught error:
```
import kipoi
model = kipoi.get_model("lsgkm-SVM/Tfbs/Ejund")
[snip most of the traceback]
ValueError: File path doesn't exists: /Users/zamparol/.kipoi/models/lsgkm-SVM/Tfbs/Ejund/model{'.yaml', '.yml'}
```

I'll file a separate issue about this tho.

**Comment by krrome** [comment]
I am sorry about the wrong DOI, will correct that ASAP. In terms of templates for implementation for training and data preprocessing / loading please take a look at the `model.py` and `dataloader.py`files.

**Comment by Avsecz** [comment]
https://github.com/kipoi/models/blob/master/lsgkm-SVM/template/model.py and https://github.com/kipoi/models/blob/master/lsgkm-SVM/template/dataloader.py

**Comment by lzamparo** [comment]
This can be safely closed, I think.
