### ISSUE TITLE
ls-gkmsvm model does not load 

### ISSUE THREAD

**Issue by lzamparo** [kipoi/models#103]
with kipoi and all dependencies installed via conda, I'm trying to load ls-gkmsvm for a particular TF (JunD).  A gist with the traceback info [is here](https://gist.github.com/lzamparo/8f59952f045da80a0d479df0ab74b1ba).  

I'm using the pattern laid out in the [Python quick start](http://kipoi.org/docs/using/01_Getting_started/#python-quick-start) guide, is there some way I'm not calling get_model correctly?

**Comment by krrome** [comment]
this is because "lsgkm-SVM/Tfbs/Ejund" is not a model, you will have to chose the exact model "lsgkm-SVM/Tfbs/Ejund/K562/Uchicago_Control". You can get the correct name either from the website by clicking on a model-category name until you reach the site that contains the installation and prediction instructions or by navigating locally in subfolders  of your directory "/Users/zamparol/.kipoi/models/" until you reach a directory containing a `model.yaml` file.

**Comment by lzamparo** [comment]
Got it, thanks.  In the case where there is only one yaml model file below a directory prefix, as in the example here, do you think it makes sense for `pull_model` to find it by using `os.walk` or something like that?  If more than one is found, then maybe a more sensible error could be returned. 

Alternatively, it would be helpful for this advice, that you need to provide a directory path containing a .yaml file to `get_model`, to appear in the Python quick start guide.

Thanks again,

**Comment by Avsecz** [comment]
Great! Thanks for the feedback. I implemented the pull for all sub-models im 0.3.7. (https://github.com/kipoi/kipoi/pull/302). We could do the same for get_model as you suggested but report a warning/error if the exact model was not found. 

We plan to improve the docs in the next few weeks. If you have any other suggestions can you please either directly submit a PR to the docs change (see kipoi/kipoi/docs) or open an issue to kipoi/kipoi? I can give you push access to the repository if you find forking painful.

**Comment by lzamparo** [comment]
@Avsecz sure, I'm happy to submit a PR for the docs on this issue.  A straightforward fork & PR should be fine, and it looks like just building the docs is pretty straightforward.  I'm glad to contribute to this effort!

**Comment by Avsecz** [comment]
Great. Thanks! I added you to both of the repositories - you can edit files on the github repo website directly. The website with docs will get updated automatically after the PR gets merged.

**Comment by lzamparo** [comment]
PR submitted: kipoi/kipoi#308

In the process of building the docs, I ran into a `sed` related problem: the fancy bash function wrapping `sed` in `render_ipynb.bash` fails unless you have gnu-sed installed.  It failed without any obvious errors in Mac OS X 10.12, anyhow.  After figuring this out, installed gnu-sed via homebrew, and made a copy of the `render_ipynb.bash` that instead calls `sed` from `/usr/local/bin` (where homebrew installs `gnu-sed`).   Not sure if we should note this somewhere?  Maybe docs/Readme.md?

**Comment by Avsecz** [comment]
Thanks!

Oh. I thought sed is installed on any unix distribution. Agree. If you have a good solution for max-osx please write a short note to docs/README.md

**Comment by lzamparo** [comment]
It is installed, but the version of sed installed on Mac OS X 10.12 does not work with that regular expression.  I have no idea why, but have encountered similar bugs before (where standard GNU utilities break on a script, only to find that the reason is older BSD utilities on my system versus updated GNU orthologs)

**Comment by akundaje** [comment]
Yes OSX grep and sed syntax are different than standard Unix. @ziga
Probably best to use Python functions to perform the same operations.

**Comment by lzamparo** [comment]
+1 for @akundaje 's suggestion.  For a quick fix, `gnu sed` is available through [conda forge](https://anaconda.org/conda-forge/sed), which keeps dependencies within the scope of `conda`.

But as someone who had to try to parse that chain of regular expressions, there is surely a more readable way to do the path rearrangement.

**Comment by Avsecz** [comment]
I added the instructions to https://github.com/kipoi/kipoi/blob/master/docs/README.md for OS-x. @lzamparo can you update the instructions with `conda`?

**Comment by Avsecz** [comment]
Ok I updated the description to install gnu-sed.

**Comment by lzamparo** [comment]
Done.  Though I edited out the suggestion to modify the script.  If gnu sed is installed via conda, it should supercede the standard OS X `sed`

**Comment by lzamparo** [comment]
Seems you beat me to the commit :)

**Comment by Avsecz** [comment]
Oh. Sorry:)

**Comment by lzamparo** [comment]
This issue can be safely closed, I think.
