### ISSUE TITLE
`kipoi test` doesn't work with "templated" models

### ISSUE THREAD

**Issue by stefanches7** [kipoi/models#112]
See screenshot
![screenshot from 2018-09-05 18-20-29](https://user-images.githubusercontent.com/17748742/45107046-9e7bd280-b138-11e8-99e5-31a5d44b8d7a.png)

**Comment by stefanches7** [comment]
Well it's actually avoidable by launching `kipoi test` in submodels

**Comment by Avsecz** [comment]
@stefanches7, please write some more info: which commands were executed and what's the Kipoi version.

**Comment by stefanches7** [comment]
I've executed `kipoi test .` on a model directory with 2 submodels inside. Kipoi version 0.4.0

**Comment by Avsecz** [comment]
Yup. You have to run tests for each model independently. Are the CLI arguments misleading?

**Comment by Avsecz** [comment]
Updated the cli arguments in https://github.com/kipoi/kipoi/pull/333. closing the issue
