### ISSUE TITLE
Exception message in kipoi test not clear

### ISSUE THREAD

**Issue by stefanches7** [kipoi/models#113]
![screenshot from 2018-09-05 18-27-40](https://user-images.githubusercontent.com/17748742/45107333-8bb5cd80-b139-11e8-9b97-4bd21e3e1caf.png)

**Comment by Avsecz** [comment]
Can you show your model.yaml?

**Comment by stefanches7** [comment]
@Avsecz my bad, it was the fact that I put (n,) as shape.
It's wasn't clear that there should stand the shape of only one item though. Maybe there is some way to make it more clear.

**Comment by Avsecz** [comment]
From http://kipoi.org/docs/contributing/02_Writing_model.yaml/:
![image](https://user-images.githubusercontent.com/10011161/45269212-91d5e200-b48a-11e8-8cff-bea14e14456d.png)

Can we close this issue?

**Comment by stefanches7** [comment]
@Avsecz maybe put this comment up to the model schema and make it "NB!"?

**Comment by stefanches7** [comment]
Otherwise yes, can also just close
