### ISSUE TITLE
How do I delete the environment created by `kipoi env`? 

### ISSUE THREAD

**Issue by Licko0909** [kipoi/models#145]
How do I delete the environment created by `kipoi env`? I am using `conda remove -name xxx --all` command does not work.

![image](https://user-images.githubusercontent.com/27897166/53689946-e56f1b80-3d9b-11e9-86d0-84e8bd6d7b43.png)
![image](https://user-images.githubusercontent.com/27897166/53689948-f029b080-3d9b-11e9-8f6f-521fff9fe2a3.png)

**Later, I used the `kipoi env -h`, using `kipoi env remove lsgkm-SVM`,** but it shows that it will delete another environment that is not related to lsgkm-SVM, as follows:
![image](https://user-images.githubusercontent.com/27897166/53690048-17817d00-3d9e-11e9-81b7-462b657b1f77.png)

**Comment by Avsecz** [comment]
Try `conda remove -n lsgkm-SVM` (e.g. witout `--all`)?

**Comment by Licko0909** [comment]
> Try `conda remove -n lsgkm-SVM` (e.g. without `--all`)?

Hahah!  `conda remove -n lsgkm-SVM --all`  Successful!
