### ISSUE TITLE
Fine-tune Basset from kipoi/models on a new dataset?

### ISSUE THREAD

**Issue by yding9** [kipoi/models#181]
Hello Kipoi members,

I want to use Basset from kipoi/models to fine-tune on a new dataset but I could not find the script. Could you provide the model fine-tune code?

Thank you so much in advance! Any help is highly appreciated!

**Comment by DerThorsten** [comment]
Hi sorry for the late response:
Here is an example how to retrain/finetune a keras model:
https://kipoi.org/docs/tutorials/python-api/#re-train-the-keras-model and
https://gist.github.com/fchollet/7eb39b44eb9e16e59632d25fb3119975
For Basset, which is uses a PyTorch model, similar code is needed.
Note that kipoi does not provide an API to train/retrain/finetune models, therefore you have to use the underlying pytorch model directly.
