### ISSUE TITLE
SeqVec environments resolve everywhere except in circleci nightly test

### ISSUE THREAD

**Issue by haimasree** [kipoi/models#251]
For some reason, circleci cannot create conda environments for SeqVec models. It keeps failing with return code -9 which points to out of memory error. I am unable to reproduce this error locally, both with ssh into circleci test session and running a local circleci build. There does not seem to be any problem with the environment. The docker executor in circleci allows 4 GB memory under the free plan so there is no way to increase memory and check if it is indeed due to less available memory. I will write to circleci and will check how much memory is conda consuming in my local setup. For now, I am removing them from the nightly test until we can come up with a solution.

**Comment by Hoeze** [comment]
You can try using Mamba or Micromamba:
https://github.com/mamba-org/mamba
It's a C++ reimplementation of conda and therefore much faster and probably also less memory-consuming :smile:

**Comment by haimasree** [comment]
I like mamba too. However, kipoi intrinsically uses conda to create environments - so that would mean kipoi needs to update. This is not out of scope  entirely but definitely a more involved solution.

**Comment by haimasree** [comment]
This seems to happen intermittently.

**Comment by haimasree** [comment]
We are keeping seqvec out of ci for now with no immediate way of resolution. There is a  [docker image for seqvec](https://hub.docker.com/layers/haimasree/kipoi-docker/seqvec/images/sha256-ed777152a1e26ee85cd5d9cfefb7217dc318d2d532cf428ddde6e073162c0196?context=repo) which still seems to be working. This image get tested every sunday and gets re-built and tested (pushed if different) once every month as part of scheduled monitoring and maintenance of kipoi docker images. I will reopen this issue if the problem appears there.

**Comment by haimasree** [comment]
Now that I have successfully added a machine executor which has more memory than a docker executor, once all docker executors replaced with machine executors, adding back SeqVec is worth trying I think.
