### ISSUE TITLE
chromVar

### ISSUE THREAD

**Issue by gagneur** [kipoi/models#63]
Adding chromVar, https://github.com/GreenleafLab

**Comment by akundaje** [comment]
ChromVar doesn't really produce a 'model' AFAIK. It's a pipeline to
identify motifs associated with variable chromatin accessible sites across
many samples. How were you envisioning putting it in the model zoo.

**Comment by gagneur** [comment]
As a post-processing tool, leveraging the TF binding site predictive models we offer. I see this is not a 'model'.

**Comment by akundaje** [comment]
Ah ok
