### ISSUE TITLE
pytorch-cpu package not found on Mac

### ISSUE THREAD

**Issue by pjshort** [kipoi/models#81]
Hello, I am trying to run the following command:

> kipoi env create DeepSEA/variantEffects

And am getting the following error:

Solving environment: ...working... failed

ResolvePackageNotFound: 
  - pytorch-cpu[version='>=0.2.0']

Traceback (most recent call last):
  File "/Users/ps14/anaconda3/bin/kipoi", line 11, in <module>
    sys.exit(main())
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/cli/env.py", line 302, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/cli/env.py", line 226, in cli_create
    kipoi.conda.create_env_from_file(env_file)
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/conda.py", line 78, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=True)
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/conda.py", line 162, in _call_conda
    return _call_command("conda", extra_args, use_stdout)
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/conda.py", line 149, in _call_command
    raise subprocess.CalledProcessError(return_code, cmd_list)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/94afb1e6/kipoi-DeepSEA__variantEffects.yaml']' returned non-zero exit status 1.

I have tried using conda to install pytorch-cpu, but it does not seem to be available from any channels.

I can install it just fine on linux, but it does not seem to be available on mac. Thank you for your help!!

**Comment by Avsecz** [comment]
Oh, I see. Seems that for os-x pytorch doesn't provide two separate repositories (see https://pytorch.org/ and select MacOS as well as Cuda=None), hence pytorch should be installed instead of pytorch-cpu. The easiest way to modify this is to edit the file: `~/.kipoi/models/DeepSEA/variantEffects/model.yaml` and replace `pytorch-cpu` with `pytorch` locally

**Comment by Avsecz** [comment]
I'll fix this in this issue: https://github.com/kipoi/kipoi/issues/271 and handle this automatically.

**Comment by Avsecz** [comment]
Just made a new kipoi release implementing this feature. Update kipoi locally: 
- `pip install -U kipoi`

and then run the command again:

```bash
kipoi env create DeepSEA/variantEffects
```

Test if everything works:
```bash
source activate kipoi-DeepSEA__variantEffects
kipoi test DeepSEA/variantEffects --source=kipoi
```

**Comment by pjshort** [comment]
Thank you! I am progressing much further along now, although there is another mac-specific error I am encountering when trying to build the pysam dependency:

/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/include -arch x86_64 -I/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/include -arch x86_64 -I/private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam/htslib -I/private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam/samtools -I/private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam/samtools/lz4 -I/private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam/bcftools -I/private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam/pysam -I/private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam -I/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/include/python3.5m -c htslib/cram/cram_io.c -o build/temp.macosx-10.6-x86_64-3.5/htslib/cram/cram_io.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    htslib/cram/cram_io.c:63:10: fatal error: 'os/lzma_stub.h' file not found
    #include "os/lzma_stub.h"
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-record-v8x017l3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/sr/9zlrqqqx7zs05_bslj6vr5w0000fvj/T/pip-install-afz115bb/pysam/

CondaValueError: pip returned an error

Traceback (most recent call last):
  File "/Users/ps14/anaconda3/bin/kipoi", line 11, in <module>
    sys.exit(main())
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/cli/env.py", line 307, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/cli/env.py", line 231, in cli_create
    kipoi.conda.create_env_from_file(env_file)
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/conda.py", line 78, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=True)
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/conda.py", line 162, in _call_conda
    return _call_command("conda", extra_args, use_stdout)
  File "/Users/ps14/anaconda3/lib/python3.6/site-packages/kipoi/conda.py", line 149, in _call_command
    raise subprocess.CalledProcessError(return_code, cmd_list)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/9fe89a89/kipoi-DeepSEA__variantEffects.yaml']' returned non-zero exit status 1.

I believe this is an issue on Macs that has been noticed before, and is probably resolved by switching to pysam version 0.13 instead of 0.14 (see https://github.com/pysam-developers/pysam/issues/645). It looks like the build is collecting pysam from 'genomelake' and I am not sure exactly how to modify that to specify pysam==0.13 instead of 0.14.1 (or if that is even the right solution!).

Collecting pysam (from genomelake->-r /tmp/kipoi/envfiles/9fe89a89/condaenv._cvub_97.requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fc/9b/4bb8d016406dcff47e2866e14d3dcb10741ec3920649e8c521996830944f/pysam-0.14.1.tar.gz

Thank you for all of your help!

**Comment by Avsecz** [comment]
Can you try installing it from bioconda? `conda install -c bioconda pysam`

**Comment by krrome** [comment]
Hi Patrick,

Would you mind trying to install pysam first via bioconda and then
additionally via pip? Perhaps that helps.

Best,
Roman

**Comment by krrome** [comment]
Also please try the conda version of pybedtools please if you have trouble
with that. `conda install -c bioconda pybedtools`


On 18 May 2018 10:41, "Roman Kreuzhuber" <rkreuzh@gmail.com> wrote:

Hi Patrick,

Would you mind trying to install pysam first via bioconda and then
additionally via pip? Perhaps that helps.

Best,
Roman

**Comment by pjshort** [comment]
Hi Roman and Ziga,

I have tried installing pysam/pybedtools with bioconda and pip as you describe above, but it looks like it is still collecting pysam v 0.14.1 from genome-lake (rather than using the pysam already on my local machine).

Thanks for all of your help and sorry for the trouble!

**Comment by krrome** [comment]
hmm I'm very sorry about that. I can play around tomorrow on my mac and see what I have to do to get it to work so that you don't have to be the guinea pig for that.

**Comment by krrome** [comment]
Hi Patrick, sorry to keep you waiting - unfortunately I could not replicate the exact error you are having with the genomelake installation. If you are willing to play around more:

1) start out with a new environment for e.g. python 3.6 as you had it. and `source activate` your new environment.
2) run `pip install kipoi[vep]`
3) run `kipoi env install DeepSEA/variantEffects`
4) run `kipoi test DeepSEA/variantEffects --source kipoi`

On the mac on which I can test only has an old OSX installed (10.9.4) and I get pysam errors, first: https://github.com/pysam-developers/pysam/issues/645, so I ran `conda install -c bioconda pysam=0.13` which then failed again because of this https://github.com/pysam-developers/pysam/issues/308 which is an ancient issue that should have been solved apparently. So it seems that there is a problem with pysam and OSX.

I assume your mac is more up to date and please let me know if you have more luck. I will in the mean time work on a solution to avoid pysam.
Thank you!

**Comment by Avsecz** [comment]
@pjshort which osx version do you have? We have put genomelake to bioconda recently. Does it work for you: `conda install genomelake -c bioconda` and then `echo 'from genomelake import extractors' | python`

**Comment by pjshort** [comment]
@Avsecz this works for me! Thanks so much for all of your help!

**Comment by Avsecz** [comment]
Cool! Does the above command causing error work as well?

**Comment by pjshort** [comment]
@Avsecz, yes it does - installing genomelake looks like it resolved the above error for me!

**Comment by Avsecz** [comment]
Ok. I'll close the issue
