### ISSUE TITLE
A ValueError when attempting to run Basenji

### ISSUE THREAD

**Issue by jeffmylife** [kipoi/models#84]
When I attempt to run the Basenji model as in the [example](http://kipoi.org/models/Basenji/), this shows up: 

`
>>> pred = model.pipeline.predict_example()
  0%|                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/kipoi/pipeline.py", line 84, in predict_example
    pred_list.append(self.model.predict_on_batch(batch['inputs']))
  File "/anaconda3/lib/python3.6/site-packages/kipoi/model.py", line 1310, in predict_on_batch
    feed_dict=merge_dicts(feed_dict, self.const_feed_dict))
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 131072, 4) for Tensor 'inputs:0', which has shape '(2, 131072, 4)'
`
![screen shot 2018-05-31 at 3 24 09 pm](https://user-images.githubusercontent.com/25440288/40803448-a7f0d7aa-64e6-11e8-9d38-3aaded38166f.png)

This occurred again when attempting to run the 

> (kipoi-Basenji) nsheng-mbp:Basenji jeffrey$ kipoi predict Basenji \
>   --dataloader_args='{'intervals_file': 'example_files/intervals.bed', 'fasta_file': 'example_files/hg38_chr22.fa'}' \
>   -o '/tmp/Basenji.example_pred.tsv'

![screen shot 2018-05-31 at 3 25 26 pm](https://user-images.githubusercontent.com/25440288/40803584-fc23959c-64e6-11e8-8e74-1a0b3a2ec49d.png)

Not sure how to fix this one. Any help is appreciated.

**Comment by Avsecz** [comment]
Hi, add a flag: `--batch_size=2`. The current implementation of basenji hardcodes the batch size.

**Comment by Avsecz** [comment]
I'll fix the code snippet on the website soon: https://github.com/kipoi/website/issues/69

**Comment by jeffmylife** [comment]
I believe this worked for me. 
Thank you for being so quick.
